//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conta.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public long AsientoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Ej { get; set; }
        public int Nro { get; set; }
        public int Subd { get; set; }
        public int CuentaID { get; set; }
        public decimal Tl { get; set; }
        public string Moneda { get; set; }
        public string Detalle { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual NomenReferencia NomenReferencia { get; set; }
    }
}
