//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conta.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosManuale
    {
        public long AsientoManual { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Ej { get; set; }
        public int Subd { get; set; }
        public string Descripcion { get; set; }
        public bool AsientoCuadrado { get; set; }
    }
}
