//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conta.Domain.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenReferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NomenReferencia()
        {
            this.Asientos = new HashSet<Asiento>();
        }
    
        public int Nro { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> TipoContabilidadID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asientos { get; set; }
        public virtual TipoContabilidade TipoContabilidade { get; set; }
    }
}
